In [1]:
import os
import boto3

%matplotlib inline
import matplotlib.pyplot as pltt
import numpy as np
import pandas as pd

# Linear Algebra with Numpy

In [2]:
a = np.array([1, 3, 2, 4])

In [3]:
a

array([1, 3, 2, 4])

In [4]:
type(a)

numpy.ndarray

In [7]:
A = np.array([[3, 1, 2],
             [2, 3, 4]])

B = np.array([[0, 1],
             [2, 3],
             [4, 5]])

C = np.array([[0, 1],
             [2, 3],
             [4, 5],
             [0, 1],
             [2, 3],
             [4, 5]])

print("A is a {} matrix".format(A.shape))
print("B is a {} matrix".format(B.shape))
print("C is a {} matrix".format(C.shape))

A is a (2, 3) matrix
B is a (3, 2) matrix
C is a (6, 2) matrix


In [8]:
A[0]

array([3, 1, 2])

In [10]:
C[2, 0]

4

In [11]:
B[:, 0]

array([0, 2, 4])

# Elementwise Operations

In [12]:
3 * A

array([[ 9,  3,  6],
       [ 6,  9, 12]])

In [13]:
A + A

array([[6, 2, 4],
       [4, 6, 8]])

In [14]:
A * A

array([[ 9,  1,  4],
       [ 4,  9, 16]])

In [15]:
A - A

array([[0, 0, 0],
       [0, 0, 0]])

In [16]:
A + B

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [17]:
A * B

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

# Dot Product

In [18]:
A.shape

(2, 3)

In [19]:
B.shape

(3, 2)

In [20]:
A.dot(B)

array([[10, 16],
       [22, 31]])

In [21]:
np.dot(A,B)

array([[10, 16],
       [22, 31]])

In [22]:
B.dot(A)

array([[ 2,  3,  4],
       [12, 11, 16],
       [22, 19, 28]])

In [23]:
A


array([[3, 1, 2],
       [2, 3, 4]])

In [24]:
B

array([[0, 1],
       [2, 3],
       [4, 5]])

In [25]:
C.shape

(6, 2)

In [26]:
C.dot(A)

array([[ 2,  3,  4],
       [12, 11, 16],
       [22, 19, 28],
       [ 2,  3,  4],
       [12, 11, 16],
       [22, 19, 28]])